//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catch
    {
        public int CatchID { get; set; }
        public int AmountOfCatch { get; set; }
        public double TripLenght { get; set; }
        public int TripStartDate { get; set; }
        public int ShipID { get; set; }
    
        public virtual Ship Ship { get; set; }
    }
}
